### ISSUE TITLE
Add decay and cram for apple on arm

### ISSUE THREAD

**Issue by bennibbelink** [pyne/data#26]
A recent [cyclus PR](https://github.com/cyclus/cyclus/pull/1814) adds support for macOS on arm.  Cyclus depends on data from this repository.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I think we may upload the cram and decay binary files here for apple arm. Then, we may not need to use the --slow tag for this.

**Comment by bennibbelink** [comment]
Closed by #27
